version: "2"
services:
  clp-scheduler:
    image: mcuadros/ofelia:latest
    container_name: clp-scheduler
    depends_on:
      - clp-all
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    labels:
      ofelia.job-run.clp-all.schedule: 0 30 22 * * *
      ofelia.job-run.clp-all.container: clp-all
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  clp-all:
    image: x1ao4/chinese-localization-for-plex:latest
    container_name: clp-all
    command: python chinese-localization-for-plex.py --all
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /自定义目录/chinese-localization-for-plex/config:/app/config
  clp-new:
    image: x1ao4/chinese-localization-for-plex:latest
    container_name: clp-new
    command: python chinese-localization-for-plex.py --new
    ports:
      - 8088:8088
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /自定义目录/chinese-localization-for-plex/config:/app/config
    restart: unless-stopped
networks: {}