version: "3.3"
services:
  quark-auto-save:
    image: cp0204/quark-auto-save:latest
    container_name: quark-auto-save
    ports:
      - 5005:5005
    environment:
      WEBUI_USERNAME: "自定义管理员账号"
      WEBUI_PASSWORD: "自定义管理员密码"
    volumes:
      - /自定义配置文件的存储目录/quark-auto-save/config:/app/config
    restart: unless-stopped
networks: {}
