version: "3.8"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
networks: {}
