version: "3.8"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /自定义目录/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
networks: {}
