version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /自定义目录/dockge/data:/app/data
      - /自定义目录/dockge/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    restart: unless-stopped
networks: {}
